language: 
  - node_js
  - ruby
node_js: '11'
ruby: '2.5'
branches:
  only:
  - master
cache:
  directories:
    - node_modules
    - vendor
    - .bundle
install:
  - gem install bundler
  - npm install
script:
  - npm run build
