language: 
  - node_js
  - ruby
branches:
  only:
  - master
cache:
  directories:
    - node_modules
    - vendor
    - .bundle
install:
  - gem install bundler
  - npm install
script:
  - npm run build
